[package]
name = "as2_python_api"
version = "0.0.0"

[package.build]
backend = { name = "pixi-build-ros", version = "*" }

[package.build.config]
extra-package-mappings = [{
  as2_motion_reference_handlers = { conda = [] },
  as2_msgs = { conda = [] },
  "python3-pydantic" = { conda = ["pydantic"] },
  "python3-pymap3d" = { conda = ["pymap3d"] },
}]

[package.host-dependencies]
as2_msgs = { path = "../as2_msgs" }
as2_motion_reference_handlers = { path = "../as2_motion_reference_handlers" }

[package.run-dependencies]
as2_msgs = { path = "../as2_msgs" }
as2_motion_reference_handlers = { path = "../as2_motion_reference_handlers" }
