[package]
name = "as2_external_object_to_tf"
version = "0.0.0"

[package.build]
backend = { name = "pixi-build-ros", version = "*" }

[package.build.config]
extra-package-mappings = [{ as2_core = { conda = [] }, as2_msgs = { conda = [] } }]

[package.host-dependencies]
as2_core = { path = "../../as2_core" }
as2_msgs = { path = "../../as2_msgs" }

[package.run-dependencies]
as2_core = { path = "../../as2_core" }
as2_msgs = { path = "../../as2_msgs" }
