# SERVICE TYPE: DynamicLand
# ------------------------------------------------------------------------------
# This service send command to start dynamic land

bool enable                         # Flag to enable land
geometry_msgs/Twist speed_limit     # speed limit (m/s)
---
bool success                        # whether it could be started or not
# ------------------------------------------------------------------------------
