# SERVICE TYPE: DynamicFollower
# ------------------------------------------------------------------------------
# This service send command to start dynamic follower

bool enable                         # Flag to enable follower
geometry_msgs/Twist speed_limit     # Speed limit (m/s)
---
bool success                        # whether it could be started or not
# ------------------------------------------------------------------------------
