# SERVICE TYPE: PackagePickUp
# ------------------------------------------------------------------------------
# This service send command to start package pickup

bool enable                             # Flag to enable pickup
geometry_msgs/Twist speed_limit         # speed limit (m/s)
---
bool success                            # whether it could be started or not
# ------------------------------------------------------------------------------