# SERVICE TYPE: PackageUnPick
# ------------------------------------------------------------------------------
# This service send command to start package unpick

bool enable                             # Flag to enable unpick
geometry_msgs/Twist speed_limit         # speed limit (m/s)
---
bool success                            # whether it could be started or not
# ------------------------------------------------------------------------------