# SERVICE TYPE: SetPlatformControlMode
# ------------------------------------------------------------------------------
# This service sets a platform control mode

as2_msgs/ControlMode control_mode       # Control mode to set
---
bool success                        # whether the control mode has been set or not
# ------------------------------------------------------------------------------
