# SERVICE TYPE: SetGeostructure
# ------------------------------------------------------------------------------
# This service creates a geoStructure (lat, lon, alt) to set in geozones node

as2_msgs/Geozone geozone  # geostructure to set
---
bool success                # whether the geoStructure has been set or not
# ------------------------------------------------------------------------------
