# SERVICE TYPE: SetSpeed
# ------------------------------------------------------------------------------
# This service sends a speed to set

as2_msgs/Speed speed        # speed to send
---
bool success                # whether the speed has been received or not
# ------------------------------------------------------------------------------
