[package]
name = "as2_behaviors_param_estimation"
version = "0.0.0"

[package.build]
backend = { name = "pixi-build-ros", version = "*" }

[package.build.config]
extra-package-mappings = [{
  as2_behavior = { conda = [] },
  as2_core = { conda = [] },
  as2_msgs = { conda = [] },
}]

[package.host-dependencies]
as2_core = { path = "../../as2_core" }
as2_msgs = { path = "../../as2_msgs" }
as2_behavior = { path = "../as2_behavior" }

[package.run-dependencies]
as2_core = { path = "../../as2_core" }
as2_msgs = { path = "../../as2_msgs" }
as2_behavior = { path = "../as2_behavior" }
