/**:
  ros__parameters:
    tf_device:
      frame_id: 'realsense_t265'
      reference_frame: 'base_link'
      x: 0.11 # meters
      y: 0.00 # meters
      z: -0.01 # meters
      roll: 0.0 # rad
      pitch: 0.680305 # rad
      yaw: 0.0 # rad
