[package]
name = "as2_keyboard_teleoperation"
version = "0.0.0"

[package.build]
backend = { name = "pixi-build-ros", version = "*" }

[package.build.config]
extra-package-mappings = [{
  as2_motion_reference_handlers = { conda = [] },
  as2_python_api = { conda = [] },
  "python3-pytest" = { conda = ["pytest"] },
}]

[package.host-dependencies]
as2_python_api = { path = "../../as2_python_api" }
as2_motion_reference_handlers = { path = "../../as2_motion_reference_handlers" }

[package.run-dependencies]
as2_python_api = { path = "../../as2_python_api" }
as2_motion_reference_handlers = { path = "../../as2_motion_reference_handlers" }
