ament_prepend_unique_value AS2_GZ_ASSETS_SCRIPT_PATH "$AMENT_CURRENT_PREFIX/share/as2_gazebo_classic_assets/scripts"

ament_prepend_unique_value GAZEBO_MODEL_PATH "$AMENT_CURRENT_PREFIX/share/as2_gazebo_classic_assets/models"
ament_prepend_unique_value GAZEBO_RESOURCE_PATH "$AMENT_CURRENT_PREFIX/share/as2_gazebo_classic_assets/worlds"
