# Follow path action definition

# Request
as2_msgs/TrajectoryWaypoints trajectory_waypoints       # trajectory
---
# Result
bool follow_path_success                                # false if failed to follow_path
---
# Feedback
float32 actual_speed                                    # actual speed (m/s)
geometry_msgs/Point next_waypoint                       # next point
uint16 remaining_waypoints                              # remaining_waypoints
float32 actual_distance_to_next_waypoint                # distance to next (m)
