# Go to waypoint action definition

# Request

as2_msgs/YawMode yaw                    # Yaw mode
geometry_msgs/PointStamped target_pose  # Goal pose 3D (m)
float32 max_speed                       # Maximum speed (m/s)
---
# Result
bool goto_success                       # False if failed to takeoff
---
# Feedback
float32 actual_speed                    # Actual speed (m/s)
float32 actual_distance_to_goal         # Distance to goal (m)
