# Navigate to Point

# Request
geometry_msgs/PointStamped point                        # Goal pose 3D (m)
as2_msgs/YawMode yaw                                    # Yaw goal mode
---
# Result
geometry_msgs/Point[] path				# Generated path
bool success                                            # Point reached?
---
# Feedback
geometry_msgs/Point[] path				# Generated path
