# Navigate to Point

# Request
geometry_msgs/PointStamped point                        # Goal pose 3D (m)
as2_msgs/YawMode yaw                                    # Yaw goal mode
---
# Result
std_msgs/Int32 path_length				# Generated path length
bool success                                            # Point reached?
---
# Feedback
geometry_msgs/Point[] path				# Generated path
