name: codecov_test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '7 7 * * *'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y lcov python3-vcstool python3-colcon-lcov-result python3-colcon-coveragepy-result python3-rosdep python3-pip python3-colcon-common-extensions
      # - name: Setup ros
      #   uses: ros-tooling/setup-ros@v0.3
      #   with:
      #     required-ros-distributions: humble
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: >
            aerostack2
            as2_alphanumeric_viewer
            as2_behavior
            as2_behaviors_motion
            as2_behaviors_path_planning
            as2_behaviors_perception
            as2_behaviors_platform
            as2_behaviors_trajectory_generation
            as2_behavior_tree
            as2_cli
            as2_core
            as2_external_object_to_tf
            as2_gazebo_assets
            as2_geozones
            as2_keyboard_teleoperation
            as2_map_server
            as2_motion_controller
            as2_motion_reference_handlers
            as2_msgs
            as2_platform_gazebo
            as2_platform_multirotor_simulator
            as2_python_api
            as2_realsense_interface
            as2_rviz_plugins
            as2_state_estimator
            as2_usb_camera_interface
            as2_visualization
          target-ros2-distro: humble
          colcon-defaults: |
            { 
              "build": {
                "mixin": ["coverage-gcc"]
              },
              "test": {
                "parallel-workers" : 1
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./ros_ws/aerostack2/codecov.yml
          # yml: ./codecov.yml
          fail_ci_if_error: false
